#!/bin/sh
start() {
  # Commands to start the application with its own script
  mem_script
}
stop() {
  # Commands to stop the application
}
case $1 in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage : $0 [start|stop]"
    exit 1
    ;;
esac
